[package]
name = "soyuz-gfx"
version.workspace = true
edition.workspace = true

[dependencies]
wgpu = { workspace = true }
winit = { workspace = true }
pollster = { workspace = true }
tracing = { workspace = true }
